patch:
  symbols:
    vvv:
      [
        👌,
        👍,
        😅,
        😭,
        ❤️,
        😢,
        🥲,
        🥹,
        😇,
        🥰,
        🫡,
        🤫,
        😐,
        🤤,
        🥵,
        🥶,
        🙁,
        😨,
        🤡,
      ]
    vface:
      [
        😀,
        😃,
        😄,
        😁,
        😆,
        😅,
        🤣,
        😂,
        🙂,
        🙃,
        🫠,
        😉,
        😊,
        😇,
        🥰,
        😍,
        🤩,
        😘,
        😗,
        😚,
        😙,
        🥲,
        😋,
        😛,
        😜,
        🤪,
        😝,
        🤑,
        🤗,
        🤭,
        🫢,
        🫣,
        🤫,
        🤔,
        🫡,
        🤐,
        🤨,
        😐,
        😑,
        😶,
        🫥,
        😶‍🌫️,
        😏,
        😒,
        🙄,
        😬,
        😮‍💨,
        🤥,
        🫨,
        😌,
        😔,
        😪,
        🤤,
        😴,
        😷,
        🤒,
        🤕,
        🤢,
        🤮,
        🤧,
        🥵,
        🥶,
        🥴,
        😵,
        😵‍💫,
        🤯,
        🤠,
        🥳,
        🥸,
        😎,
        🤓,
        🧐,
        😕,
        🫤,
        😟,
        🙁,
        😮,
        😯,
        😲,
        😳,
        🥺,
        🥹,
        😦,
        😧,
        😨,
        😰,
        😥,
        😢,
        😭,
        😱,
        😖,
        😣,
        😞,
        😓,
        😩,
        😫,
        🥱,
        😤,
        😡,
        😠,
        🤬,
        😈,
        👿,
        💀,
        ☠️,
        💩,
        🤡,
        👹,
        👺,
        👻,
        👽,
        👾,
        🤖,
        😺,
        😸,
        😹,
        😻,
        😼,
        😽,
        🙀,
        😿,
        😾,
        🙈,
        🙉,
        🙊,
      ]
  vhand:
    [
      👍,
      👎,
      👌,
      🤌,
      🤏,
      ✌️,
      🤞,
      🫰,
      🤟,
      🤘,
      🤙,
      👈,
      👉,
      👆,
      👇,
      ☝️,
      ✋,
      🤚,
      🖐️,
      🖖,
      👋,
      🤝,
      🙏,
    ]
  vheart:
    [❤️, 🧡, 💛, 💚, 💙, 💜, 🖤, 🤍, 🤎, 💔, ❣️, 💕, 💞, 💓, 💗, 💖, 💘, 💝]
  vanimal:
    [
      🐶,
      🐱,
      🐭,
      🐹,
      🐰,
      🦊,
      🐻,
      🐼,
      🐨,
      🐯,
      🦁,
      🐮,
      🐷,
      🐸,
      🐵,
      🐔,
      🐧,
      🐦,
      🦆,
      🦅,
    ]
  vfood:
    [
      🍏,
      🍎,
      🍐,
      🍊,
      🍋,
      🍌,
      🍉,
      🍇,
      🍓,
      🫐,
      🍈,
      🍒,
      🍑,
      🥭,
      🍍,
      🥥,
      🥝,
      🍅,
      🥑,
      🍆,
    ]
